version: '3'
services:

  #PHP Service
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: digitalocean.com/php
#     container_name: app
#     restart: unless-stopped
#     tty: true
#     environment:
#       SERVICE_NAME: app
#       SERVICE_TAGS: dev
#     working_dir: /var/www
#     networks:
#       - app-network

  #Nginx Service
  nginx:
    build:
        context: ./containers/nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
        - ./:/var/www
        - ./containers/logs/nginx/:/var/log/nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    build:
        context: ./containers/php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "9000"
    networks:
      - app-network
  # composer:
  #   build:
  #       context: ./
  #   container_name: composer
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - ./:/var/www
  #   depends_on:
  #     - php-fpm
  #   # working_dir: /var/www
  #   # command: install
  #   networks:
  #     - app-network

  #MySQL Service
#   db:
#     image: mysql:5.7.22
#     container_name: db
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: your_mysql_root_password
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     networks:
#       - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
